### ISSUE TITLE
Correctly guess maintainer

### ISSUE THREAD

**Issue by karthik** [karthik/holepunch#16]
> The user now defaults to "karthik" whereas before it was correctly guessing "Anna" for me. Now have to remember to set this manually.

From #8

**Comment by karthik** [comment]
@annakrystalli The function does take maintainer as an arg. So if you want Anna, then this works:

```r
 write_dockerfile(maintainer = "Anna")
```

Not sure how it guessed before.  I've modified the function to read `usethis.full_name` from options first, then check to see it's passed to the function, otherwise goes to Unknown.

**Comment by annakrystalli** [comment]
Sorry yes, by manually I meant I had to use the`maintainer` argument to override the default `"karthik"`. Works a treat for me now, with my full name `'Anna Krystall'` appearing. 😃👍
