### ISSUE TITLE
missing namespace definition in function build_binder

### ISSUE THREAD

**Issue by ajstewartlang** [karthik/holepunch#22]
Running `build_binder()` generated an error associated with the `plan()` function:

`Error in plan("list") : could not find function "plan"`

Looking at the script we noticed that two occurrences of plan were not preceded by `future::`  We fixed this locally, and were going to make a PR.  But then we noticed an additional (new) error was generated (see next issue).

**Comment by karthik** [comment]
Thank you. will fix this shortly.
