### ISSUE TITLE
future error with build_binder()

### ISSUE THREAD

**Issue by ajstewartlang** [karthik/holepunch#23]
After resolving the namespace issue (#22), we encountered a new error that looks related to the future package:

`later: exception occurred while executing callback: 
Evaluation error: Cannot resolve MultisessionFuture (<none>), because the connection to the worker is corrupt: Connection (connection: description="NA", class="NA", mode="NA", text="NA", opened="NA", can read="NA", can write="NA", id=434) is no longer valid. There is currently no registered R connection with that index 3.`

We do not know how to resolve this but just thought we'd let you know!

**Comment by karthik** [comment]
This is fixed for now. I will add appropriate handling for unfulfilled promises in a future commit.
