### ISSUE TITLE
Error during `build_binder` when files are uncommitted

### ISSUE THREAD

**Issue by annakrystalli** [karthik/holepunch#25]
Throwing an error and refusing to build if there is *any* uncommitted file seems a bit strict to me. Perhaps it's just my messy working but sometimes I do have uncommitted files that I might never commit but don't want in my gitignore either.

I feel like it should either be a warning or warn you of the fact that there are uncommitted changes and ask you whether you'd like to proceed.  What do you reckon?

In addition, using the package seems to add files to the workspace that are usually gitignored, for example the `.Rhistory` file.

**Comment by karthik** [comment]
Im happy to switch that to a warning. My current rationale is that after someone adds a description, a dockerfile, and then proceeds to build without committing (and pushing them) will see Binder using repo2docker to start the slow painful process of doing this from scratch. 

Is it worth checking if `Dockerfile` and `DESCRIPTION` are dirty and suggest committing those?

**Comment by karthik** [comment]
> In addition, using the package seems to add files to the workspace that are usually gitignored, for example the .Rhistory file.

That should not be the case. This package does not touch either file. Are you sure the `.Rhistory` isn't just local to you?

**Comment by karthik** [comment]
OK I switched it to a warning for now.

**Comment by annakrystalli** [comment]
Sorry for delay! Yesterday was a bit hectic.

I feel the most useful would be to ask the user to confirm they still want to proceed if there are uncommitted files using `usethis::ui_yeah()`, giving them a chance to sort that out before launching a build. 


***

Regarding funny things popping up into the workspace, it's definitely causing some unexpected behaviours for me.  For example, I just reran `write_compendium_description()` and now I also have an another file that oddly looks like it's modified:

![image](https://user-images.githubusercontent.com/5583057/60337901-34207100-999c-11e9-9bf3-976ea7f6f4a4.png)

![image](https://user-images.githubusercontent.com/5583057/60338030-a09b7000-999c-11e9-8401-9e7097b2cf8f.png)


DOH! I think I figured it out! It's actually an issue with `binder-test` repo. There's an `.Rproj.user/` in the template repo where it seems information that gets overwritten during use of the package is cached. Perhaps that's what's masking the global behaviour I've set for ignoring`.Rhistory` too?

**Comment by karthik** [comment]
> I feel the most useful would be to ask the user to confirm they still want to proceed if there are uncommitted files using usethis::ui_yeah(), giving them a chance to sort that out before launching a build.

This is implemented in the [uiyeah branch](https://github.com/karthik/holepunch/tree/uiyeah). I'll test it more before merging to master but it does implement the behavior you describe.  https://github.com/karthik/holepunch/blob/uiyeah/R/build.R#L50-L60

**Comment by annakrystalli** [comment]
Just played around with it and I really like this implementation 😃. My only suggestion would be to tweak the text to read:

```
There are uncommitted files in your repo. Until committed and pushed to GitHub, Binder cannot build from these files. Do you still wish to continue?
```
just so the `ui_yeah` options make sense.

**Comment by karthik** [comment]
Thanks Anna! Updated in the [pr](https://github.com/karthik/holepunch/pull/26). If that was the last big issue, I'll go ahead and merge if you give me an ok.

**Comment by annakrystalli** [comment]
Good to go from me! 👍🚀
