### ISSUE TITLE
Running projects on a newer R version

### ISSUE THREAD

**Issue by harell** [karthik/holepunch#28]
Thank you for a great package.

I'm using today's date where the newest R version is 3.6.0 and still get a much older R version when launching the server 

Is there a way to control the R version installed in the Docker container?

![image](https://user-images.githubusercontent.com/7226303/61075513-40153400-a46e-11e9-845b-0a50688081e4.png)

**Comment by karthik** [comment]
Thanks for this report. Can you point me to a repo if it's public so I can see what's happening?

> Is there a way to control the R version installed in the Docker container?

Yes. You can see date bins for R versions with this:

```
holepunch:::r_version_table
```

Then choose a date between start and end that matches the version you desire. Does that help?

**Comment by harell** [comment]
Thanks. Here is a link
https://github.com/data-science-competitions/modeling.earthquake.damage

**Comment by nuest** [comment]
The new default R version in repo2docker is now `3.6` and you can even choose the R version in `runtime.txt`, see https://github.com/jupyter/repo2docker/pull/772

This is not online on mybinder.org yet !

@harell detecting the R version base on the MRAN date is not supported. Can you elaborate where the time interval above is coming from?

**Comment by harell** [comment]
Hi @nuest 

The time interval comes from running @karthik suggestion: 

```
holepunch:::r_version_table
```

**Comment by harell** [comment]
Hi @nuest and @karthik 

The package behaves as expected. Sorry for the trouble.

1. The problem was in the project deployment sequence. After creating binder, there was no commit of the binder file.
2. I added MRAN support using the following script. Please consider whether it's worth sharing with others. Using this script, the R version and the package versions available at that time, are aligned.

Within `install.R`:

```
# Helper Functions --------------------------------------------------------
set_repos_to_MRAN <- function(){
    options(repos = get_MRAN_URL())
}

get_MRAN_URL <- function(){
    MRAN_timestamp <- get_binder_timestamp()
    paste0("https://mran.microsoft.com/snapshot/", MRAN_timestamp)
}

get_binder_timestamp <- function(){
    file_path <- list.files(pattern = "runtime.txt", full.names = TRUE, recursive = TRUE, all.files = TRUE)
    as.Date(gsub("^r-", "", readLines(file_path, 1)))
}

# Install Packages --------------------------------------------------------
set_repos_to_MRAN()
install.packages(<package 1>)
install.packages(<package 2>)
...
install.packages(<package n>)

```

Thank you for the support
