### ISSUE TITLE
Build failing with NB_USER

### ISSUE THREAD

**Issue by kelshmo** [karthik/holepunch#33]
[My build](https://mybinder.org/v2/gh/kelshmo/nature-functional-data/master?urlpath=rstudio) is failing on `RUN chown -R ${NB_USER} ${HOME}` and I believe it is due to an undefined NB_USER. NB_USER is an empty variable in this environment.

[Here is the Docker file source code](https://github.com/kelshmo/nature-functional-data/blob/master/.binder/Dockerfile) generated with `make_dockerfile()`.

I reviewed you instructions, but I am not seeing where/how to specify NB_USER. 

Thanks for your work on this package!

**Comment by karthik** [comment]
Hi @kelshmo 
Can you switch your base on your [Dockerfile](https://github.com/kelshmo/covarr/blob/master/Dockerfile#L1) from 

```
FROM rocker/tidyverse
```

to 

```
FROM rocker/binder:3.6.0
```

and see what happens?

**Comment by kelshmo** [comment]
Hi @karthik, that change did resolve my problem with NB_USER, thanks for the prompt response. 

I see a binder base is [recommended](https://karthik.github.io/holepunch/reference/write_dockerfile.html), is it in fact required?

**Comment by karthik** [comment]
To work with mybinder, yes unfortunately. While you can spin up a Docker container just fine with your old image, binder needs Jupyterhub specific elements which are included in the binder base. It also contains tidyverse (and the whole kitchen sink of dependencies). So starting from there, adding your bioconductor packages, and using that as a base for binder will ensure the fastest/working deployment.

**Comment by kelshmo** [comment]
Cool - thanks for the clarification.
