### ISSUE TITLE
Specifying package versions

### ISSUE THREAD

**Issue by bapalmer** [karthik/holepunch#37]
I love this package and how easy it was to set up an initial instance, but now I'd like to go one step further...

When writing the docker file I set the `r_date` to a year ago just to ensure that the R version that gets loaded matches that of the [example project](https://github.com/bapalmer/RSS_Belfast_2019) I'm working with. 

I figure that the package versions loaded will align to the specified `r_date`, but is it possible to read the output of a file generated from `sessionInfo()` so that the exact package versions could be incorporated into the Binder instance?

I'm thinking of faithfully replicating the R environment for downstream integrity of the research.

**Comment by karthik** [comment]
Hi @bapalmer,
Thanks very much for your note and the kind words.

> I figure that the package versions loaded will align to the specified r_date

That's right. The `r_date` is already being used to download packages from [MRAN](https://mran.microsoft.com/documents/rro/reproducibility#snapshot) time machine matching that date (not the current latest version of the package).

> but is it possible to read the output of a file generated from sessionInfo() so that the exact package versions could be incorporated into the Binder instance?

The exact packages versions *are* being downloaded with the current approach of holepunch. We don't use `session_info()` for a variety of reasons.

1. If you turn binder on for an old project, your current `session_info` will not match the package versions used in the old project.
2. `session_info` includes all packages that are loaded into your current environment, not just the ones use for a specific project. For example, I have several local use only helper packages always loaded. I don't want them ending up in the Dockerfile/DESCRIPTION files of my projects. So I believe `holepunch` has the right approach of parsing all R/Rmd files and picking out only those packages used for a particular project.

> I'm thinking of faithfully replicating the R environment for downstream integrity of the research.

If you call libraries explicitly (using `library` or `require`) or via namespace (using `::` or `:::`) in your code, all of it will get faithfully captured by `holepunch` (let me know if that isn't the case). 

Let me know if this makes sense or if I can clarify further.

**Comment by bapalmer** [comment]
I was just imagining a scenario where one package hadn't been updated for some time and you wanted to specify the package version number. In my `description` file there is an argument...
> Depends: 
    summarytools,
    tidyverse

Could it be amended so that all the packages are set to the `r_date` but versions could be specified if required?

I've no experience building packages or how hard this may be to implement but I can see how it might be beneficial in some circumstances.

Anyway, this is only a suggestion. Thanks again.


> Depends: 
    (summarytools, version = 0.9.1),
    tidyverse

**Comment by karthik** [comment]
> I was just imagining a scenario where one package hadn't been updated for some time and you wanted to specify the package version number.

I see your point. 

> Could it be amended so that all the packages are set to the r_date but versions could be specified if required?

Unfortunately R does not allow for specifying exact versions of packages in the dependency list. You can specify a minimum version ([example](https://github.com/karthik/holepunch/blob/master/DESCRIPTION#L27)) but that's about it. It's a limitation of the R ecosystem. With holepunch I'm doing my best to get users as close as possible to accurately capturing their setup. I personally think it's good practice to keep packages up to date, unless there is a strong reason you want to use an old version of a package.

**Comment by bapalmer** [comment]
Colleagues on the bioinformatics side of the house have some horror stories where packages/software (not necessarily R) update mid-project. In more extreme cases the results can invert between software versions, although this is perhaps more of an insight with respect underlying problems in the field more so than anything we can control for here.
