### ISSUE TITLE
Update write_runtime to support R version

### ISSUE THREAD

**Issue by nuest** [karthik/holepunch#41]
repo2docker also supports setting an R version in `runtime.txt` [now](), see https://repo2docker.readthedocs.io/en/latest/config_files.html#runtime-txt-specifying-runtimes

`r-<RVERSION>-<YYYY>-<MM>-<DD>`

Can be added to `write_runtime()`, maybe with a default to the version used in the current session?

**Comment by karthik** [comment]
Support added. Thanks @nuest!
