### ISSUE TITLE
can we write the dockerfile to binder/

### ISSUE THREAD

**Issue by benmarwick** [karthik/holepunch#6]
I recently learned from @seabbs that we can put Dockerfiles for binder in a `binder/` directory:

> Can I put my configuration files outside the root of my repository?
> Yes! Configuration files may be placed in the root of your repository or in a binder/ folder in the root of your repository (i.e. myproject/binder/). If a binder/ folder is used, Binder will only read configuration files from that location (i.e. myproject/binder/requirements.txt) and will ignore those in the repository’s root (myproject/environment.yml and myproject/requirements.txt).

https://mybinder.readthedocs.io/en/latest/faq.html#can-i-put-my-configuration-files-outside-the-root-of-my-repository

Learning that made me wonder what you think about making that an option for `write_dockerfile` (or even a default?).

Some advantages that I can see are that:

-  the user has a meaningfully-named item in their repo (`binder/` for binder), and
- the user can have another top-level Dockerfile for other purposes, such as CI with circle-ci, etc. 

Just a thought!

**Comment by karthik** [comment]
Very cool idea. Happy to implement this in a update. 

cc @choldgraf Does this seem ok with you?

**Comment by karthik** [comment]
Also learned that it can go in `.binder/` so I'll follow that convention from now on.

**Comment by karthik** [comment]
@benmarwick Thanks for this great suggestion. It seems to work nicely. Can you reinstall this package and give this example (https://github.com/karthik/binder-test) a go?

**Comment by benmarwick** [comment]
Great! I think it looks quite elegant to have the `.binder`, good find! 

I've tested `binder-test` here https://github.com/benmarwick/holepunch-testing
```
> library(holepunch)
> # 🚫🚨No need for install.r or runtime.txt 🚨 🚫
> write_compendium_description()
✔ Setting active project to '/Users/bmarwick/Desktop/holepunch-testing'
✔ Writing 'DESCRIPTION'
> # to write a description, with dependencies listed 
> write_dockerfile() 
> # To write a dockerfile (more on how to adapt this)
> generate_badge()
● Copy and paste the following lines into '/Users/bmarwick/Desktop/holepunch-testing/README.md':
  <!-- badges: start -->
  [![Launch Rstudio binder](http://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/benmarwick/holepunch-testing/master?urlpath=rstudio)
  <!-- badges: end -->
  [Copied to clipboard]
Warning message:
In readLines(path) :
  incomplete final line found on '/Users/bmarwick/Desktop/holepunch-testing/README.md'
> 
> # At this time push the code to GitHub 🙌
> 
> # And click on the badge on your README or use
> build_binder()
$phase
[1] "built"

$imageName
[1] "gcr.io/binder-prod/r2d-f18835fd-benmarwick-2dholepunch-2dtesting-9c1316:0f005e8d6479bcc81887c5431d1dbf4843a947b9"

$message
[1] "Found built image, launching...\n"

$phase
[1] "launching"

$message
[1] "Launching server...\n"

$phase
[1] "ready"

$message
[1] "server running at https://hub.gke.mybinder.org/user/benmarwick-holepunch-testing-ij6ofg28/\n"

$image
[1] "gcr.io/binder-prod/r2d-f18835fd-benmarwick-2dholepunch-2dtesting-9c1316:0f005e8d6479bcc81887c5431d1dbf4843a947b9"

$repo_url
[1] "https://github.com/benmarwick/holepunch-testing"

$token
[1] "x2h_c4lERru6_-_5CADdNw"

$url
[1] "https://hub.gke.mybinder.org/user/benmarwick-holepunch-testing-ij6ofg28/"

[1] "All done!"
NULL
[1] "https://mybinder.org/build/gh/benmarwick/holepunch-testing/master"
```

and it just works fine!

![image](https://user-images.githubusercontent.com/1262179/59391018-d9461300-8d27-11e9-8c64-64acd3207c67.png)

**Comment by karthik** [comment]
This is now fixed. All binder files now write to `.binder/`
